name: release
on:
  push:
    tags:
      - '*.*.*'

jobs:
  release:
    name: publish releases
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Golang
        uses: actions/setup-go@v2
        with:
          go-version: '^1.15'
      - name: Build
        run: |
          chmod +x ./build.sh
          ./build.sh
      - name: Upload to release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            release/goqut-linux
            release/goqut-macos
            release/goqut-windows.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}